### ISSUE TITLE
Support for inline requests methods

### ISSUE THREAD

**Issue by sovietspaceship2** [unwind-protect/cl-telegram-bot#4]
This depends on this: https://github.com/unwind-protect/telegram-bot-api-schema as the functions are compiled from the scheme API description. The compiler should be updated to parse and emit those definitions as well.

**Comment by sovietspaceship** [comment]
Use https://github.com/tranql/telegram-bot-api-schema instead of my repo, as mine is unmaintained and that one is more recent and up-to-date.
