### ISSUE TITLE
Calling get-updates in a loop makes the software crashes

### ISSUE THREAD

**Issue by cage2** [unwind-protect/cl-telegram-bot#5]
Hello,

When a drakma http request uses `:want-stream t` a stream is returned; as far as i can see in `get-updates` the stream is never closed, this results in a great number of socket opened that keeps growing until an error 'to many file openened' is raised. Eventually the software crashes.

Please consider the patch you can find at this mirror (the last commit should mitigate this issue).

https://notabug.org/cage/cl-telegram-bot

Bye.
C.

**Comment by sovietspaceship2** [comment]
You're right. Will merge your fix as soon as possible. If you can make a pull request here it would help.

**Comment by cage2** [comment]
Thank you!

I am a bit recluctant to make a fork here on github, is ok for you if i sent the patch to a your personal email?

You can find mine here: https://notabug.org/cage/cl-pslib/src/master/README#L136 :))

Or I can attach the patch here if you prefer.

Bye and thank you again!
C.

**Comment by sovietspaceship2** [comment]
It's ok. I just want your contribution to appear here so you're given proper credit for it.

**Comment by sovietspaceship2** [comment]
Merged, thank you. If you want, with your permission, I would merge your other changes.

**Comment by cage2** [comment]
Hello!

Sure you can apply the other changes! :)

Bye.
C.

**Comment by cage2** [comment]
Hello,

Also please merge the last commit.

Bye!
C.
